name: Deployment to aws dev environment

on:
  push:
    branches:
      - main
    tags:
      - dev
      - test

jobs:
  deploy:
    name: Build and Deploy App to Dev
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    concurrency:
      group: deploy-${{github.ref_name}}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch/tag name
        run: echo "ENV_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Print local env
        run: make print-env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ca-central-1
          role-to-assume: ${{ env.AWS_SA_ROLE_ARN }}
          role-duration-seconds: 900
          role-session-name: ci-deployment

      - name: NextJS Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build app
        run: make build-prod-app

      - name: Deploy infra
        run: make deploy

      - name: Deploy app
        run: make deploy-app
