name: test gh vars

on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - main
    tags:
      - dev
      - test

jobs:
  deploy:
    name: test gh vars
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Branch name
        run: echo $GITHUB_REF

      - name: Branch/Tag name
        run: echo $GITHUB_REF_NAME
